"use strict";

require("@babel/polyfill");
window.onload = function () {
  var body = document.querySelector('body');
  var article = document.createElement('article');
  article.classList.add("animated", "bounce");
  var h2 = document.createElement('h2');
  var p1 = document.createElement('p');
  var progress = document.createElement('progress');
  var span1 = document.createElement('span');
  var br1 = document.createElement('br');
  var br2 = document.createElement('br');
  var p2 = document.createElement('p');
  var a1 = document.createElement('a');
  var p3 = document.createElement('p');
  var a2 = document.createElement('a');
  h2.textContent = 'El partido agoniza';
  p1.textContent = 'Minuto 85, en un contragolpe que Javier ha iniciado luego de un tiro de esquina a favor del rival se le presentan dos opciones:';
  progress.setAttribute('max', '100');
  progress.setAttribute('value', '42');
  span1.textContent = '42%';
  p2.textContent = 'Tirar a portería (se encuentra a 25m del arco, pero el portero está un poco adelantado).';
  a1.href = 'tercer-paso-uno.html';
  a1.textContent = 'Siguiente';
  p3.textContent = 'Pasarsela a el lateral izquierdo de su equipo y correr hacia el centro.';
  a2.href = 'tercer-paso-dos.html';
  a2.textContent = 'Siguiente';
  body.appendChild(article);
  article.appendChild(h2);
  article.appendChild(p1);
  article.appendChild(progress);
  article.appendChild(span1);
  article.appendChild(br1);
  article.appendChild(br2);
  article.appendChild(p2);
  article.appendChild(a1);
  article.appendChild(br1);
  article.appendChild(p3);
  article.appendChild(a2);
};